apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aiops-iforest.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "aiops-iforest.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "aiops-iforest.name" . }}
    spec:
      containers:
        - name: model-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "aiops-iforest.fullname" . }}-config
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
